# Generated by Django 4.2.4 on 2023-12-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_text',
            field=models.TextField(default=''),
        ),
    ]
