# Generated by Django 4.2.4 on 2023-12-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_description_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_text',
        ),
    ]
